# Generated by Django 4.0.6 on 2022-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=68)),
                ('email', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=128)),
            ],
        ),
    ]
